# Generated by Django 5.0.6 on 2024-06-09 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelatihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('penyelenggara', models.CharField(max_length=255)),
                ('tahun', models.CharField(max_length=4)),
            ],
        ),
    ]
